/**
 * Drizzle ORM schema — PostgreSQL
 * Collaborative Project Management Platform
 *
 * Design notes:
 * - Every tenant-scoped table carries `workspace_id` (denormalized onto `tasks`
 *   and `activity_logs` even though it's derivable via `project_id`) so RLS
 *   policies and hot-path indexes never need a join to establish tenancy.
 * - All PKs are UUID v4 (gen_random_uuid()), generated by Postgres, not the app,
 *   so bulk imports / replication don't depend on app-side ID generation.
 * - Enums are Postgres native enums (not varchar + check) for storage
 *   efficiency and to get free validation at the DB layer.
 */

import {
  pgTable,
  pgEnum,
  uuid,
  varchar,
  text,
  boolean,
  timestamp,
  integer,
  jsonb,
  uniqueIndex,
  index,
  doublePrecision,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const workspaceTypeEnum = pgEnum("workspace_type", ["PERSONAL", "SHARED"]);

export const workspaceRoleEnum = pgEnum("workspace_role", [
  "OWNER",
  "ADMIN",
  "MEMBER",
  "GUEST",
]);

export const projectVisibilityEnum = pgEnum("project_visibility", [
  "PUBLIC_TO_WORKSPACE",
  "PRIVATE_TO_MEMBERS",
]);

export const projectRoleEnum = pgEnum("project_role", [
  "PROJECT_ADMIN",
  "EDITOR",
  "VIEWER",
]);

export const invitationStatusEnum = pgEnum("invitation_status", [
  "PENDING",
  "ACCEPTED",
  "DECLINED",
  "EXPIRED",
  "REVOKED",
]);

export const taskStatusEnum = pgEnum("task_status", [
  "BACKLOG",
  "TODO",
  "IN_PROGRESS",
  "IN_REVIEW",
  "DONE",
  "ARCHIVED",
]);

export const taskPriorityEnum = pgEnum("task_priority", [
  "LOW",
  "MEDIUM",
  "HIGH",
  "URGENT",
]);

export const dependencyTypeEnum = pgEnum("dependency_type", [
  // Matches standard Gantt dependency semantics (MS Project / Asana Timeline):
  // successor can't start until predecessor finishes, etc.
  "FINISH_TO_START",
  "START_TO_START",
  "FINISH_TO_FINISH",
  "START_TO_FINISH",
]);

// ---------------------------------------------------------------------------
// users
// ---------------------------------------------------------------------------

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: varchar("email", { length: 320 }).notNull(),
  passwordHash: text("password_hash"), // null when the user only ever signs in via OAuth
  fullName: varchar("full_name", { length: 200 }).notNull(),
  avatarUrl: text("avatar_url"),
  emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
  // Platform-wide bypass of workspace/project membership checks — see
  // db/rls-policies.sql's is_super_admin() and auth/super-admin.ts. Not
  // exposed through any signup flow; only ever set by a trusted operator
  // (scripts/seed-superadmin.ts, or a direct DB update).
  isSuperAdmin: boolean("is_super_admin").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  emailUnique: uniqueIndex("users_email_unique_idx").on(t.email),
}));

// ---------------------------------------------------------------------------
// workspaces
// ---------------------------------------------------------------------------

export const workspaces = pgTable("workspaces", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: varchar("name", { length: 200 }).notNull(),
  type: workspaceTypeEnum("type").notNull(),
  ownerId: uuid("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  slug: varchar("slug", { length: 220 }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  slugUnique: uniqueIndex("workspaces_slug_unique_idx").on(t.slug),
  ownerIdx: index("workspaces_owner_idx").on(t.ownerId),
  // A user may have at most one PERSONAL workspace — enforced at app layer
  // via a partial unique index (Drizzle can't express WHERE clauses on
  // uniqueIndex directly, so this is also declared in the companion
  // migration SQL: CREATE UNIQUE INDEX ... WHERE type = 'PERSONAL').
}));

// ---------------------------------------------------------------------------
// workspace_members
// ---------------------------------------------------------------------------

export const workspaceMembers = pgTable("workspace_members", {
  workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  role: workspaceRoleEnum("role").notNull().default("MEMBER"),
  // When a user is added to a workspace *only* as a side effect of a
  // project-level invite, this flag is true and the membership is scoped —
  // see project_members for the actual grant. Prevents a project guest from
  // browsing other projects in the workspace via a full membership row.
  isProjectScopedGuest: uuid("scoped_to_project_id").references(() => projects.id, { onDelete: "cascade" }),
  joinedAt: timestamp("joined_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  pk: uniqueIndex("workspace_members_pk").on(t.workspaceId, t.userId),
  userIdx: index("workspace_members_user_idx").on(t.userId),
  workspaceRoleIdx: index("workspace_members_workspace_role_idx").on(t.workspaceId, t.role),
}));

// ---------------------------------------------------------------------------
// clients — a workspace's roster of external parties (customers, matters,
// retainers). Exists so professional-services use cases (legal, consulting,
// agency work) can treat "the client" as a first-class thing with its own
// contact info and a running history of engagements, rather than just a
// free-text label on a project. A project's client is optional — plenty of
// projects (internal ops, a solo freelancer's own product) have no client.
// ---------------------------------------------------------------------------

export const clients = pgTable("clients", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
  name: varchar("name", { length: 200 }).notNull(),
  primaryContactName: varchar("primary_contact_name", { length: 200 }),
  primaryContactEmail: varchar("primary_contact_email", { length: 320 }),
  notes: text("notes"),
  createdBy: uuid("created_by").notNull().references(() => users.id),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  workspaceIdx: index("clients_workspace_idx").on(t.workspaceId),
}));

// ---------------------------------------------------------------------------
// projects
// ---------------------------------------------------------------------------

export const projects = pgTable("projects", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
  // Nullable — a project is a "client engagement" when this is set (the
  // legal/consultancy framing the dashboard leans into), but plenty of
  // projects (internal ops, a solo freelancer's own product) have no client.
  clientId: uuid("client_id").references(() => clients.id, { onDelete: "set null" }),
  name: varchar("name", { length: 200 }).notNull(),
  description: text("description"),
  visibility: projectVisibilityEnum("visibility").notNull().default("PRIVATE_TO_MEMBERS"),
  createdBy: uuid("created_by").notNull().references(() => users.id),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  workspaceIdx: index("projects_workspace_idx").on(t.workspaceId),
  workspaceVisibilityIdx: index("projects_workspace_visibility_idx").on(t.workspaceId, t.visibility),
  clientIdx: index("projects_client_idx").on(t.clientId),
}));

// ---------------------------------------------------------------------------
// project_members
// ---------------------------------------------------------------------------

export const projectMembers = pgTable("project_members", {
  projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  role: projectRoleEnum("role").notNull().default("VIEWER"),
  addedAt: timestamp("added_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  pk: uniqueIndex("project_members_pk").on(t.projectId, t.userId),
  userIdx: index("project_members_user_idx").on(t.userId),
}));

// ---------------------------------------------------------------------------
// project_invitations
// ---------------------------------------------------------------------------

export const projectInvitations = pgTable("project_invitations", {
  id: uuid("id").primaryKey().defaultRandom(),
  projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
  inviterId: uuid("inviter_id").notNull().references(() => users.id),
  inviteeEmail: varchar("invitee_email", { length: 320 }).notNull(),
  inviteeUserId: uuid("invitee_user_id").references(() => users.id, { onDelete: "set null" }),
  role: projectRoleEnum("role").notNull().default("VIEWER"),
  token: varchar("token", { length: 128 }).notNull(), // sha256 hex of the raw token; raw token only ever lives in the email link
  status: invitationStatusEnum("status").notNull().default("PENDING"),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  tokenUnique: uniqueIndex("project_invitations_token_unique_idx").on(t.token),
  projectStatusIdx: index("project_invitations_project_status_idx").on(t.projectId, t.status),
  inviteeEmailIdx: index("project_invitations_invitee_email_idx").on(t.inviteeEmail),
  inviteeUserIdx: index("project_invitations_invitee_user_idx").on(t.inviteeUserId),
}));

// ---------------------------------------------------------------------------
// tasks
// ---------------------------------------------------------------------------

export const tasks = pgTable("tasks", {
  id: uuid("id").primaryKey().defaultRandom(),
  projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), // denormalized for RLS + index locality
  // Self-reference for subtasks (Asana/ClickUp-style one level of nesting is
  // enforced at the app layer, not the DB — Postgres has no easy CHECK for
  // "depth <= 1", and real PM tools rarely need more than one level anyway).
  // The callback form (AnyPgColumn) is required for self-referencing FKs in
  // Drizzle since `tasks` isn't in scope yet at this point in its own definition.
  parentTaskId: uuid("parent_task_id").references((): AnyPgColumn => tasks.id, { onDelete: "cascade" }),
  title: varchar("title", { length: 300 }).notNull(),
  description: text("description"),
  status: taskStatusEnum("status").notNull().default("TODO"),
  priority: taskPriorityEnum("priority").notNull().default("MEDIUM"),
  assigneeId: uuid("assignee_id").references(() => users.id, { onDelete: "set null" }),
  reporterId: uuid("reporter_id").notNull().references(() => users.id),
  // startDate + dueDate together define the Gantt bar; startDate is
  // optional (a task can have only a due date, same as most PM tools) but
  // required for that task to render as a bar rather than a milestone diamond.
  startDate: timestamp("start_date", { withTimezone: true }),
  dueDate: timestamp("due_date", { withTimezone: true }),
  // Fractional-index positioning (e.g. "a0", "a1", "a0m") avoids re-writing
  // every row in a column on each drag-and-drop reorder.
  position: doublePrecision("position").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  projectStatusPositionIdx: index("tasks_project_status_position_idx").on(t.projectId, t.status, t.position),
  assigneeIdx: index("tasks_assignee_idx").on(t.assigneeId),
  workspaceIdx: index("tasks_workspace_idx").on(t.workspaceId),
  dueDateIdx: index("tasks_due_date_idx").on(t.dueDate),
  parentTaskIdx: index("tasks_parent_task_idx").on(t.parentTaskId),
}));

// ---------------------------------------------------------------------------
// task_dependencies — powers the Gantt view's blocking relationships.
// predecessor must (per `type`) reach the relevant milestone before the
// successor can — same model as MS Project / Asana Timeline.
// ---------------------------------------------------------------------------

export const taskDependencies = pgTable("task_dependencies", {
  id: uuid("id").primaryKey().defaultRandom(),
  predecessorTaskId: uuid("predecessor_task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }),
  successorTaskId: uuid("successor_task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }),
  type: dependencyTypeEnum("type").notNull().default("FINISH_TO_START"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  uniquePair: uniqueIndex("task_dependencies_unique_pair_idx").on(t.predecessorTaskId, t.successorTaskId),
  successorIdx: index("task_dependencies_successor_idx").on(t.successorTaskId),
}));

// ---------------------------------------------------------------------------
// task_comments — flat discussion thread per task (no nested replies; every
// best-of-class tool's task activity feed is effectively flat + @mentions,
// which is a notification concern, not a data-modeling one, so left out of
// v1).
// ---------------------------------------------------------------------------

export const taskComments = pgTable("task_comments", {
  id: uuid("id").primaryKey().defaultRandom(),
  taskId: uuid("task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }),
  authorId: uuid("author_id").notNull().references(() => users.id),
  body: text("body").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  editedAt: timestamp("edited_at", { withTimezone: true }),
}, (t) => ({
  taskTimeIdx: index("task_comments_task_time_idx").on(t.taskId, t.createdAt),
}));

// ---------------------------------------------------------------------------
// activity_logs
// ---------------------------------------------------------------------------

export const activityLogs = pgTable("activity_logs", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }),
  projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }),
  userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }),
  action: varchar("action", { length: 100 }).notNull(), // e.g. "task.status_changed", "invite.accepted"
  metadata: jsonb("metadata").notNull().default({}),
  timestamp: timestamp("timestamp", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  workspaceTimeIdx: index("activity_logs_workspace_time_idx").on(t.workspaceId, t.timestamp),
  projectTimeIdx: index("activity_logs_project_time_idx").on(t.projectId, t.timestamp),
}));

// ---------------------------------------------------------------------------
// Relations (for Drizzle's relational query API — db.query.projects.findMany({ with: {...} }))
// ---------------------------------------------------------------------------

export const usersRelations = relations(users, ({ many }) => ({
  ownedWorkspaces: many(workspaces),
  workspaceMemberships: many(workspaceMembers),
  projectMemberships: many(projectMembers),
  assignedTasks: many(tasks, { relationName: "assignee" }),
}));

export const workspacesRelations = relations(workspaces, ({ one, many }) => ({
  owner: one(users, { fields: [workspaces.ownerId], references: [users.id] }),
  members: many(workspaceMembers),
  projects: many(projects),
}));

export const workspaceMembersRelations = relations(workspaceMembers, ({ one }) => ({
  workspace: one(workspaces, { fields: [workspaceMembers.workspaceId], references: [workspaces.id] }),
  user: one(users, { fields: [workspaceMembers.userId], references: [users.id] }),
}));

export const clientsRelations = relations(clients, ({ one, many }) => ({
  workspace: one(workspaces, { fields: [clients.workspaceId], references: [workspaces.id] }),
  createdByUser: one(users, { fields: [clients.createdBy], references: [users.id] }),
  projects: many(projects),
}));

export const projectsRelations = relations(projects, ({ one, many }) => ({
  workspace: one(workspaces, { fields: [projects.workspaceId], references: [workspaces.id] }),
  client: one(clients, { fields: [projects.clientId], references: [clients.id] }),
  members: many(projectMembers),
  tasks: many(tasks),
  invitations: many(projectInvitations),
}));

export const projectMembersRelations = relations(projectMembers, ({ one }) => ({
  project: one(projects, { fields: [projectMembers.projectId], references: [projects.id] }),
  user: one(users, { fields: [projectMembers.userId], references: [users.id] }),
}));

export const projectInvitationsRelations = relations(projectInvitations, ({ one }) => ({
  project: one(projects, { fields: [projectInvitations.projectId], references: [projects.id] }),
  workspace: one(workspaces, { fields: [projectInvitations.workspaceId], references: [workspaces.id] }),
  inviter: one(users, { fields: [projectInvitations.inviterId], references: [users.id] }),
  inviteeUser: one(users, { fields: [projectInvitations.inviteeUserId], references: [users.id] }),
}));

export const tasksRelations = relations(tasks, ({ one, many }) => ({
  project: one(projects, { fields: [tasks.projectId], references: [projects.id] }),
  workspace: one(workspaces, { fields: [tasks.workspaceId], references: [workspaces.id] }),
  assignee: one(users, { fields: [tasks.assigneeId], references: [users.id] }),
  reporter: one(users, { fields: [tasks.reporterId], references: [users.id] }),
  parentTask: one(tasks, { fields: [tasks.parentTaskId], references: [tasks.id], relationName: "subtasks" }),
  subtasks: many(tasks, { relationName: "subtasks" }),
  comments: many(taskComments),
  dependenciesAsPredecessor: many(taskDependencies, { relationName: "predecessor" }),
  dependenciesAsSuccessor: many(taskDependencies, { relationName: "successor" }),
}));

export const taskDependenciesRelations = relations(taskDependencies, ({ one }) => ({
  predecessor: one(tasks, {
    fields: [taskDependencies.predecessorTaskId],
    references: [tasks.id],
    relationName: "predecessor",
  }),
  successor: one(tasks, {
    fields: [taskDependencies.successorTaskId],
    references: [tasks.id],
    relationName: "successor",
  }),
}));

export const taskCommentsRelations = relations(taskComments, ({ one }) => ({
  task: one(tasks, { fields: [taskComments.taskId], references: [tasks.id] }),
  author: one(users, { fields: [taskComments.authorId], references: [users.id] }),
}));

export const activityLogsRelations = relations(activityLogs, ({ one }) => ({
  workspace: one(workspaces, { fields: [activityLogs.workspaceId], references: [workspaces.id] }),
  project: one(projects, { fields: [activityLogs.projectId], references: [projects.id] }),
  user: one(users, { fields: [activityLogs.userId], references: [users.id] }),
}));

// Convenience TS types
export type User = typeof users.$inferSelect;
export type Workspace = typeof workspaces.$inferSelect;
export type WorkspaceMember = typeof workspaceMembers.$inferSelect;
export type Client = typeof clients.$inferSelect;
export type Project = typeof projects.$inferSelect;
export type ProjectMember = typeof projectMembers.$inferSelect;
export type ProjectInvitation = typeof projectInvitations.$inferSelect;
export type Task = typeof tasks.$inferSelect;
export type TaskDependency = typeof taskDependencies.$inferSelect;
export type TaskComment = typeof taskComments.$inferSelect;
export type ActivityLog = typeof activityLogs.$inferSelect;
